packages:
  # all packages (tooling extensions)
  - "packages/*"
  # all showcases (demo apps, libs, modules, cds-ui5 apps, ...)
  - "showcases/*"
  - "showcases/cds-bookshop/app/*"
  # docs
  - "docs"
