name: Lint Commit Message

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # See: https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HUSKY_SKIP: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
