name: Release (automatic)

on:
  push:
    branches: [main]

env:
  HUSKY_SKIP: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release): publish')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7
          run_install: |
            - args: [--frozen-lockfile]

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          npm run release:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
